// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list_products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "Vr\xE1t\xED ve\u0159ejn\xFD seznam produkt\u016F e-shopu Vapesport (ID, n\xE1zev, cena, sklad) z datab\xE1ze overrides.",
  inputSchema: {
    limit: z.number().int().min(1).max(200).optional().describe("Maximum products to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("product_overrides").select("product_id, name_override, price_override, b2b_price, stock_qty").limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_my_b2b_profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_my_b2b_profile_default = defineTool2({
  name: "get_my_b2b_profile",
  title: "Get my B2B profile",
  description: "Vr\xE1t\xED B2B profil aktu\xE1ln\u011B p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele (n\xE1zev firmy, I\u010CO, kontaktn\xED osoba, adresa, stav schv\xE1len\xED).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161en\xFD u\u017Eivatel." }], isError: true };
    }
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("b2b_profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "B2B profil nenalezen." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list_my_orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_my_orders_default = defineTool3({
  name: "list_my_orders",
  title: "List my orders",
  description: "Vr\xE1t\xED objedn\xE1vky aktu\xE1ln\u011B p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele podle e-mailu z tokenu, se\u0159azen\xE9 od nejnov\u011Bj\u0161\xED.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum orders to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161en\xFD u\u017Eivatel." }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) return { content: [{ type: "text", text: "Token neobsahuje e-mail." }], isError: true };
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("orders").select("id, order_number, created_at, email, company_name, is_b2b, payment_label, items").eq("email", email).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ysirrzvnivmiohwoftrx";
var mcp_default = defineMcp({
  name: "vapesport-mcp",
  title: "Vapesport MCP",
  version: "0.1.0",
  instructions: "N\xE1stroje pro e-shop Vapesport. `list_products` je ve\u0159ejn\xE9; `get_my_b2b_profile` a `list_my_orders` vy\u017Eaduj\xED p\u0159ihl\xE1\u0161en\xED u\u017Eivatele.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_my_b2b_profile_default, list_my_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
